import os
import json


class DocumentationGenerator:

    def __init__(self, project_path):
        self.project_path = project_path
        self.metadata_path = os.path.join(project_path, "reproflow_metadata.json")

    def load_metadata(self):
        with open(self.metadata_path) as f:
            return json.load(f)

    def generate_docs(self):

        metadata = self.load_metadata()

        language = metadata["language"]
        entry = metadata["entry_command"]

        content = f"""
# Reproducing This Experiment

## Language
{language}

## Entry Command
{entry}

## Prerequisites

- Docker installed
- Python 3.10+
- Git (optional)

## Steps to Reproduce

### 1. Scan the project

python reproflow/main.py scan {self.project_path}

### 2. Generate environment

python reproflow/main.py generate {self.project_path}

### 3. Run experiment

cd {self.project_path}
bash run.sh

### 4. Check reproducibility

python reproflow/main.py reprocheck {self.project_path}

## Outputs

Experiment results will appear in:

outputs/
repro_runs/

## Generated by ReproFlow
"""

        path = os.path.join(self.project_path, "Reproduce.md")

        with open(path, "w") as f:
            f.write(content.strip())

        print("Reproduce.md generated.")